### ISSUE TITLE
Charts/KwaliteitsKenmerken

### ISSUE THREAD

**Issue by SaleemTheKing** [SaleemTheKing/RWS-web-DD-OPER#4]
**What needs to be done**
De kwaliteitskenmerk van de opgehaalde data moet ook weergeven worden in de grafiek.

**What should it look like**
N/A

**Checklist**
- [ ] Kwaliteitskenmerk wordt weergeven in de grafiek

**Comment by SaleemTheKing** [comment]
Issue is geblokkeerd omdat ik meer informatie nodig heb over hoe ik de kwaliteitskenmerk moet laten zien in de grafiek.

**Comment by rws-zicht** [comment]
file:///tmp/hoek.zip

**Comment by rws-zicht** [comment]
[hoek.zip](https://github.com/SaleemTheKing/RWS-web-DD-OPER/files/6243257/hoek.zip)

In de events staat:

'''
            "events": [
                {
                    "timeStamp": "2021-04-01T11:20:00.000Z",
                    "startTime": "2021-04-01T11:15:00.000Z",
                    "endTime": "2021-04-01T11:25:00.000Z",
                    **"quality": 50,**
                    "value": -66,
                    **"additionalInfo": "0"**
                },

Het gaat om de velden:
 * quality
 * additionalInfo
