### ISSUE TITLE
Charts/Kwantiteiten

### ISSUE THREAD

**Issue by SaleemTheKing** [SaleemTheKing/RWS-web-DD-OPER#6]
**What needs to be done**
Laat alle kwantiteiten zien van een bepaalde locatie in de grafiek. De data moet worden weergegeven als punten in een lijngrafiek.

**What should it look like**
Per dataset moet er een andere kleur komen met een goed verschil in andere kleuren.

**Checklist**
- [x] waterlevel
- [x] waterdischarge
- [x] airtemperature
- [x] atmosphericpressure
- [x] winddirection
- [x] gateliftingheight
- [x] watertemperature
- [x] waveheigth
- [x] windspeed
- [x] waterconductivity
- [x] waterflowspeed
- [x] waterchlorisity
- [x] watercurrentspeed
- [x] wavedirection
- [x] waveenergy

**Comment by rws-zicht** [comment]
Deze lijst zijn we nog aan het aanpassen.
De discussie welke er zijn komt nog.

Het zullen er 100+ worden.
